### PR TITLE
Deprecate public ign functions in favor of gz

### PR DESCRIPTION
**Pull request by chapulina**
* Builds on top of 
    * #247
    * #252 
    * https://github.com/gazebosim/gz-cmake/pull/263
* Part of https://github.com/ignition-tooling/release-tools/issues/719

## Summary

Deprecate the `ign_` functions that are used by downstream packages and replace them with `gz_` counterparts. Warnings are commented out and will be enabled once all our libraries have migrated to `gz_`.

As far as I can tell, CMake doesn't provide a convenient way for a function to forward arguments to another. So I had to play a bit with the scopes to make sure all the values passed in and returned from a function worked correctly.

Here are the rules I came up with:

* If a function doesn't take any arguments and doesn't set or get any variables from the parent scope, it can be wrapped directly like this:

```cmake
function(ign_XXX)
    gz_XXX()
endfunction()
function(gz_XXX)
  # Exactly the same as old ign_XXX
endfunction()
```

* If a function takes named arguments, those can be forwarded directly:

```cmake
function(ign_XXX named_arg)
    gz_XXX(${named_arg})
endfunction()
function(gz_XXX)
  # Exactly the same as old ign_XXX
endfunction()
```

* If a function takes optional arguments parsed with `cmake_parse_arguments`, parse those at the old `ign_` function and skip parsing them in the new function with the help of a `skip_parsing` variable.

```cmake
function(ign_XXX named_arg)

    # Exactly same as in gz_ below
    set(options SOME_OPTION)
    set(oneValueArgs SOME_VALUE)
    set(multiValueArgs SOME_MULTIVALUE)
    cmake_parse_arguments(gz_install_all_headers "${options}" "${oneValueArgs}" "${multiValueArgs}" ${ARGN})

    set(gz_XXX_skip_parsing true)
    gz_XXX(${named_arg})
endfunction()
function(gz_XXX)

   # Skip parsing when called from ign_, otherwise parse as usual
    if (NOT gz_XXX_skip_parsing)
      set(options SOME_OPTION)
      set(oneValueArgs SOME_VALUE)
      set(multiValueArgs SOME_MULTIVALUE)
      cmake_parse_arguments(gz_install_all_headers "${options}" "${oneValueArgs}" "${multiValueArgs}" ${ARGN})
    endif()

  # The rest is exactly the same as old ign_XXX
endfunction()
```

* If a function sets values to the parent scope, those need to be bubbled up by the `ign_` wrapper function:

```cmake
function(ign_XXX)
    gz_XXX()

    set(${gz_XXX_RETURN_VALUE} ${${gz_XXX_RETURN_VALUE}} PARENT_SCOPE)
endfunction()
function(gz_XXX)
  # Exactly the same as old ign_XXX
  # Includes somewhere
  # set(${gz_XXX_RETURN_VALUE} ${calculated_value} PARENT_SCOPE)
endfunction()
```

## Test it

1. Compile the stack using this branch, and verify that everything still works the same way
1. Uncomment some of the commented warnings, then compile the stack and verify that warnings show up
1. Update downstream packages to use `gz_` instead of `ign_` and verify that they work the same, without warnings

## TODO

Keeping as draft until

- [ ] All `ign_` functions have been deprecated
- [ ] Set up CI compiling the entire stack to verify point 1 above

## Checklist
- [x] Signed all commits for DCO
- [ ] Added tests
- [x] ~~Added example and/or tutorial~~
- [ ] Updated documentation (as needed)
- [ ] Updated migration guide (as needed)
- [x] ~~Consider updating Python bindings (if the library has them)~~
- [x] `codecheck` passed (See [contributing](https://ignitionrobotics.org/docs/all/contributing#contributing-code))
- [x] All tests passed (See [test coverage](https://ignitionrobotics.org/docs/all/contributing#test-coverage))
- [x] While waiting for a review on your PR, please help review [another open pull request](https://github.com/pulls?q=is%3Aopen+is%3Apr+user%3Aignitionrobotics+repo%3Aosrf%2Fsdformat+archived%3Afalse+) to support the maintainers

**Note to maintainers**: Remember to use **Squash-Merge** and edit the commit message to match the pull request summary while retaining `Signed-off-by` messages.

🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸

### CODE REVIEW

**Comment by methylDragon** [comment]
There's a small issue with the approach you're using for bubbling parsed variables down to a `gz_` prefixed function.

I think if you have something like `ign_A` -> `gz_A` -> `gz_B`, the common `skip_parsing` variable causes `gz_B` to skip its parsing, which is not good.

I'd recommend using a prefix to mangle the names. Like `gz_b_skip_parsing`.

**Comment by chapulina** [comment]
> I'd recommend using a prefix to mangle the names. Like gz_b_skip_parsing.

Thanks for catching that, updated this PR with this pattern

**Comment by chapulina** [comment]
This PR was getting too large. Started breaking it into smaller PRs:

* https://github.com/gazebosim/gz-cmake/pull/253
* https://github.com/gazebosim/gz-cmake/pull/254
* https://github.com/gazebosim/gz-cmake/pull/255

**Comment by methylDragon** [comment]
Will approve once my local build works with this

**Review by methylDragon — APPROVED** [review]

**Pull request merged**
