### PR TITLE
Changes for OGRE-2.3

### PR DESCRIPTION
**Pull request by mjcarroll**
# 🎉 New feature

## Summary

CMake updates to make `gz-cmake` compatible with OGRE-2.3 debs built by OpenRobotics

## Test it

For linux (jammy and focal):
* Download the latest ogre-2.3 debs either from the prerelease mirror or by using the direct links from Jenkins: https://build.osrfoundation.org/job/ogre-2.3-debbuilder/27/
* Build gz-cmake

For homebrew:
* Use the new OGRE 2.3 bottle: https://github.com/osrf/homebrew-simulation/pull/1971

```
cd gz-cmake/examples/find_ogre2/ogre-2.3
mkdir build && cd build
cmake ..
```

The expected output with the debs installed

```
-- Looking for GzOGRE2 - found

-- OGRE2_FOUND: TRUE
-- OGRE2_LIBRARIES: /usr/lib/x86_64-linux-gnu/OGRE-2.3/libOgreNextMain.so
-- OGRE2_INCLUDE_DIRS: /usr/include/OGRE-2.3/usr/include/OGRE-2.3/RenderSystems/GL3Plus
-- OGRE2_VERSION: 2.3.1
-- OGRE2_VERSION_MAJOR: 2
-- OGRE2_VERSION_MINOR: 3
-- OGRE2_VERSION_PATCH: 1
-- OGRE2_RESOURCE_PATH: /usr/lib/x86_64-linux-gnu/OGRE-2.3/OGRE
-- Configuring done
-- Generating done
-- Build files have been written to: /home/mjcarroll/workspaces/gz_garden/src/gz-cmake/examples/find_ogre2/ogre-2.3/build
```

Similarly, the `ogre-2.2` demo should continue to find `2.2.5` on `jammy`.

## Checklist
- [ ] Signed all commits for DCO
- [ ] Added tests
- [ ] Added example and/or tutorial
- [ ] Updated documentation (as needed)
- [ ] Updated migration guide (as needed)
- [ ] Consider updating Python bindings (if the library has them)
- [ ] `codecheck` passed (See [contributing](https://gazebosim.org/docs/all/contributing#contributing-code))
- [ ] All tests passed (See [test coverage](https://gazebosim.org/docs/all/contributing#test-coverage))
- [ ] While waiting for a review on your PR, please help review [another open pull request](https://github.com/pulls?q=is%3Aopen+is%3Apr+user%3Agazebosim+archived%3Afalse+) to support the maintainers

**Note to maintainers**: Remember to use **Squash-Merge** and edit the commit message to match the pull request summary while retaining `Signed-off-by` messages.

### CODE REVIEW

**Review by ahcorde — CHANGES_REQUESTED** [review]
I have this issue
```
CMake Error in ogre2/src/CMakeLists.txt:
  Imported target "GzOGRE2::GzOGRE2" includes non-existent path

    "/usr/include/OGRE-2.3/OGRE"
```

I resolved with

```bash
mkdir /usr/include/OGRE-2.3/OGRE
```

is this related with this code?

**Comment by mjcarroll** [comment]
```
CMake Error in ogre2/src/CMakeLists.txt:
  Imported target "GzOGRE2::GzOGRE2" includes non-existent path

    "/usr/include/OGRE-2.3/OGRE"
```

To be clear, this was building from source and not using the debs, correct?

**Comment by ahcorde** [comment]
> ```
> CMake Error in ogre2/src/CMakeLists.txt:
>   Imported target "GzOGRE2::GzOGRE2" includes non-existent path
> 
>     "/usr/include/OGRE-2.3/OGRE"
> ```
> 
> To be clear, this was building from source and not using the debs, correct?

yes, I was compiling from source

**Comment by mjcarroll** [comment]
> yes, I was compiling from source

Can you test the debs from above and see if the error persists?

**Comment by mjcarroll** [comment]
@osrf-jenkins retest this please

**Comment by mjcarroll** [comment]
I have done test builds on all three platforms using this branch.

**Review by scpeters — APPROVED** [review]

**Review by ahcorde — APPROVED** [review]

**Pull request merged**
