### PR TITLE
Use visibility hidden by default

### PR DESCRIPTION
**Pull request by j-rivero**
# 🎉 New feature

Part of #166 

**Note:** all Ionic branches need to be checked and fixed before merging.

## Summary

The commit changes the gz-cmake projects to use C/C++ visibility hidden by default. This is a potential breaking changed for projects using  gz-cmake but the benefits in terms of creating portable code and time spend by the loader could be huge.
    
To avoid this change, the `EXPOSE_SYMBOLS_BY_DEFAULT` flag can be used in the gz_configure_project call.

The change deprecates the `HIDDEN_SYMBOLS_BY_DEFAULT` flag.

## Test it

Create an Ionic colcon workspace and build it with this branch.

## Checklist
- [x] Signed all commits for DCO
- [ ] Added tests
- [ ] Added example and/or tutorial
- [ ] Updated documentation (as needed)
- [ ] Updated migration guide (as needed)
- [ ] Consider updating Python bindings (if the library has them)
- [ ] `codecheck` passed (See [contributing](https://gazebosim.org/docs/all/contributing#contributing-code))
- [ ] All tests passed (See [test coverage](https://gazebosim.org/docs/all/contributing#test-coverage))
- [ ] While waiting for a review on your PR, please help review [another open pull request](https://github.com/pulls?q=is%3Aopen+is%3Apr+user%3Agazebosim+archived%3Afalse+) to support the maintainers

**Note to maintainers**: Remember to use **Squash-Merge** and edit the commit message to match the pull request summary while retaining `Signed-off-by` messages.

### CODE REVIEW

**Comment by azeey** [comment]
This is a good example of a PR that needs CI runs on all downstream libraries building this PR from source. Cross-ref https://github.com/gazebo-tooling/release-tools/issues/851

**Comment by scpeters** [comment]
> This is a good example of a PR that needs CI runs on all downstream libraries building this PR from source. Cross-ref [gazebo-tooling/release-tools#851](https://github.com/gazebo-tooling/release-tools/issues/851)

example for testing with gz-utils in https://github.com/gazebosim/gz-utils/pull/115

**Comment by j-rivero** [comment]
@osrf-jenkins run tests

**Comment by j-rivero** [comment]
@osrf-jenkins run tests

**Comment by scpeters** [comment]
wow, apparently we've already been using `HIDE_SYMBOLS_BY_DEFAULT` in sdformat since https://github.com/gazebosim/sdformat/pull/780#issuecomment-994975728

**Comment by caguero** [comment]
@j-rivero , any outstanding PR in all downstream libraries that we should merge before this one?

**Comment by j-rivero** [comment]
> @j-rivero , any outstanding PR in any downstream libraries that we should merge before this one?

Nop! we are good to go.

**Comment by j-rivero** [comment]
Before merging, just found that we don't have a Migration.md entry for this, done in [75ae798](https://github.com/gazebosim/gz-cmake/pull/392/commits/75ae798af3e8fd6fcd8780c781b965d01fedc034)

**Comment by scpeters** [comment]
> > @j-rivero , any outstanding PR in any downstream libraries that we should merge before this one?
> 
> Nop! we are good to go.

actually, do we want to remove the `HIDE_SYMBOLS_BY_DEFAULT` parameter from all the downstream libraries now that we've confirmed that it works? I think if we merge this now it will add cmake deprecation warnings everywhere

**Comment by j-rivero** [comment]
> > > @j-rivero , any outstanding PR in any downstream libraries that we should merge before this one?
> > 
> > 
> > Nop! we are good to go.
> 
> actually, do we want to remove the `HIDE_SYMBOLS_BY_DEFAULT` parameter from all the downstream libraries now that we've confirmed that it works? I think if we merge this now it will add cmake deprecation warnings everywhere

Yep. See https://github.com/gazebosim/gz-cmake/issues/166#issuecomment-1887521423 and linked PRs after the comment.

**Comment by j-rivero** [comment]
Time has come. Merging :rocket:

**Review by azeey — APPROVED** [review]
LGTM! Just a few documentation related comments

**Review by j-rivero — COMMENTED** [review]
Thanks!

**Comment by oysstu** [comment]
For anyone trying the EXPOSE_SYMBOLS_BY_DEFAULT flag, the flag must be added to gz_configure_build, **not** gz_configure_project as indicated in the PR description.

@j-rivero it might be a good idea to edit the description

**Comment by j-rivero** [comment]
> @j-rivero it might be a good idea to edit the description

Done! Thanks.

**Pull request merged**
