### PR TITLE
Split gzutils into functional pieces

### PR DESCRIPTION
**Pull request by mjcarroll**
GzUtils has gotten unmaintainably large.  This splits the functions into separate files.

### CODE REVIEW

**Comment by j-rivero** [comment]
> GzUtils has gotten unmaintainably large. This splits the functions into separate files.

+1 . Side effects of merging this:
 *  it's going to be hard to do forward/backward ports from/to the `gz-cmake2` branch. Is there anything stopping us of sending this to the `gz-cmake2` branch?
 * The current open PRs will need to rebase and probably adapt new code to this change.

**Comment by mjcarroll** [comment]
> it's going to be hard to do forward/backward ports from/to the gz-cmake2 branch. Is there anything stopping us of sending this to the gz-cmake2 branch?

Hmm, good call.  I don't think there is anything stopping us from doing that here.  I may re-open this against cmake2, we can land it with `Ign` file names and then apply the renaming?

> The current open PRs will need to rebase and probably adapt new code to this change.

I think git _should_ track the split/renaming without too much issue, but let me try it on one PR first.

**Comment by j-rivero** [comment]
> > it's going to be hard to do forward/backward ports from/to the gz-cmake2 branch. Is there anything stopping us of sending this to the gz-cmake2 branch?
> 
> Hmm, good call. I don't think there is anything stopping us from doing that here. I may re-open this against cmake2, we can land it with `Ign` file names and then apply the renaming?

Yep, a bit of extra-work sorry but probably will make things easier for the future and reorganize the things on gz-cmake2 as well.

> > The current open PRs will need to rebase and probably adapt new code to this change.
> 
> I think git _should_ track the split/renaming without too much issue, but let me try it on one PR first.

Thanks, anyway we can work on solving the problems that appear.

**Comment by scpeters** [comment]
> > it's going to be hard to do forward/backward ports from/to the gz-cmake2 branch. Is there anything stopping us of sending this to the gz-cmake2 branch?
> 
> Hmm, good call. I don't think there is anything stopping us from doing that here. I may re-open this against cmake2, we can land it with `Ign` file names and then apply the renaming?
> 
> > The current open PRs will need to rebase and probably adapt new code to this change.
> 
> I think git _should_ track the split/renaming without too much issue, but let me try it on one PR first.

I think it would be easier to resolve the conflicts when merging forward if the change has been applied separately to each branch. I would be fine with merging to `gz-cmake3` first and then backporting to `ign-cmake2`. There's already a conflict on gz-cmake3 though

**Comment by scpeters** [comment]
conflicts

**Comment by j-rivero** [comment]
> conflicts

I've tried to resolve them. Mostly applied #326 in [7ceb5f6](https://github.com/gazebosim/gz-cmake/pull/344/commits/7ceb5f6d84bde26712685958d3698e0b5a5bf4d7) and #334 in [cbf5249](https://github.com/gazebosim/gz-cmake/pull/344/commits/cbf52496e0c90c5c77da5af8c984f77ed447d21c)

**Review by j-rivero — APPROVED** [review]
Good for me. @mjcarroll I leave it open until you or @scpeters give a last view on this.

**Comment by scpeters** [comment]
> Good for me. @mjcarroll I leave it open until you or @scpeters give a last view on this.

I double-checked the changes using `meld` and noticed a few small differences: see https://github.com/gazebosim/gz-cmake/pull/349. I'll be ready to approve if we merge that into this branch.

**Comment by j-rivero** [comment]
> I double-checked the changes using `meld` and noticed a few small differences: see #349. I'll be ready to approve if we merge that into this branch.

Good catch, merged!

**Comment by mjcarroll** [comment]
Thanks Steve, I think we are all good here!

**Pull request merged**
