### PR TITLE
cppcheck uses c++17

### LINKED ISSUE #378: cppcheck needs to be updated to use c++17
The version of `cppcheck` in Focal and later supports `c++17`, so we should update it.
https://github.com/gazebosim/gz-cmake/blob/87c2a5429d89987816059411d4dec8c0b3369ebd/cmake/GzCodeCheck.cmake#L20

### PR DESCRIPTION
**Pull request by sdhar04**
Closes #378 

## Summary
Changed Line 20 of /cmake/GzCodeCheck.cmake to update a cppcheck parameter from c++14 to c++17

## Test it
I don't know exactly how to make tests for this, but I'm guessing you could:
Run  `cmake -DCMAKE_CXX_CPPCHECK:FILEPATH=cppcheck .` inside a package 
Or build and make workspaces and packages where Gazebo is used

### CODE REVIEW

**Comment by azeey** [comment]
@sdhar04 Thanks for your contribution! Would you be able to check if each of the Gazebo libraries pass `cppcheck` before we merge this PR? Also, could you [signoff](https://gazebosim.org/docs/harmonic/contributing#contributing-code) on your commit so the DCO check can pass?

**Comment by sdhar04** [comment]
Hello @azeey ! Could you give me some pointers as to how I can check if a library passes cppcheck?

**Comment by scpeters** [comment]
> Hello @azeey ! Could you give me some pointers as to how I can check if a library passes cppcheck?

If you are able to build Garden or Harmonic from source in a colcon workspace (using [these instructions](https://gazebosim.org/docs/harmonic/install_ubuntu_src)), using this branch of `gz-cmake3`, then you can run `make codecheck` from each package subfolder of the workspace `build` folder (`build/gz-math7`, `build/gz-common5`, etc), I think that would do it.

**Comment by sdhar04** [comment]
I am on Ubuntu 20.04 and tried to build Garden from the tutorial. My plan was to completely install from source and then replicate the changes I had made in this PR. But `colcon build --cmake-args -DBUILD_TESTING=OFF --merge-install` is giving me an error while trying to build gz-msgs9, specifically plugins being killed by signal 11 (I haven't made the changes yet).
Is there a workaround?

**Comment by scpeters** [comment]
> I am on Ubuntu 20.04 and tried to build Garden from the tutorial. My plan was to completely install from source and then replicate the changes I had made in this PR. But `colcon build --cmake-args -DBUILD_TESTING=OFF --merge-install` is giving me an error while trying to build gz-msgs9, specifically plugins being killed by signal 11 (I haven't made the changes yet). Is there a workaround?

it sounds like you're having trouble building from source. Here are the [garden build from source instructions](https://gazebosim.org/docs/garden/install_ubuntu_src). Can you post a question on [Robotics Stack Exchange](https://robotics.stackexchange.com/) with details on your build error and then link it here so we can follow up?

**Comment by sdhar04** [comment]
Here is the [question I've asked](https://robotics.stackexchange.com/questions/107769/problem-while-building-gz-msgs9-in-ubuntu-20-04). 
It seems protoc-gen-ignmsgs is causing segmentation faults.

**Comment by sdhar04** [comment]
> Here is the [question I've asked](https://robotics.stackexchange.com/questions/107769/problem-while-building-gz-msgs9-in-ubuntu-20-04). It seems protoc-gen-ignmsgs is causing segmentation faults.

Shall I raise an issue regarding this?

**Comment by azeey** [comment]
> > Here is the [question I've asked](https://robotics.stackexchange.com/questions/107769/problem-while-building-gz-msgs9-in-ubuntu-20-04). It seems protoc-gen-ignmsgs is causing segmentation faults.
> 
> Shall I raise an issue regarding this?

Did you have a chance to try my [suggestion](https://robotics.stackexchange.com/questions/107769/problem-while-building-gz-msgs9-in-ubuntu-20-04#comment43891_107769)?

**Comment by sdhar04** [comment]
> > > Here is the [question I've asked](https://robotics.stackexchange.com/questions/107769/problem-while-building-gz-msgs9-in-ubuntu-20-04). It seems protoc-gen-ignmsgs is causing segmentation faults.
> > 
> > 
> > Shall I raise an issue regarding this?
> 
> Did you have a chance to try my [suggestion](https://robotics.stackexchange.com/questions/107769/problem-while-building-gz-msgs9-in-ubuntu-20-04#comment43891_107769)?

I did, and it's giving me the same errors

**Comment by sdhar04** [comment]
> > Hello @azeey ! Could you give me some pointers as to how I can check if a library passes cppcheck?
> 
> If you are able to build Garden or Harmonic from source in a colcon workspace (using [these instructions](https://gazebosim.org/docs/harmonic/install_ubuntu_src)), using this branch of `gz-cmake3`, then you can run `make codecheck` from each package subfolder of the workspace `build` folder (`build/gz-math7`, `build/gz-common5`, etc), I think that would do it.

I have built Gazebo from source on a cleaner Ubuntu system, and run `make codecheck` successfully from each package. The targets `cpplint`, `cppcheck`, and `codecheck` have all been built for each package.

**Comment by azeey** [comment]
> > > Hello @azeey ! Could you give me some pointers as to how I can check if a library passes cppcheck?
> > 
> > 
> > If you are able to build Garden or Harmonic from source in a colcon workspace (using [these instructions](https://gazebosim.org/docs/harmonic/install_ubuntu_src)), using this branch of `gz-cmake3`, then you can run `make codecheck` from each package subfolder of the workspace `build` folder (`build/gz-math7`, `build/gz-common5`, etc), I think that would do it.
> 
> I have built Gazebo from source on a cleaner Ubuntu system, and run `make codecheck` successfully from each package. The targets `cpplint`, `cppcheck`, and `codecheck` have all been built for each package.

Awesome, thanks!

**Review by azeey — APPROVED** [review]

**Pull request merged**
