### PR TITLE
⬆️ Bump main to 4.0.0~pre1

### PR DESCRIPTION
**Pull request by chapulina**
* Part of https://github.com/gazebo-tooling/release-tools/issues/578

### CODE REVIEW

**Comment by chapulina** [comment]
We need to fix the Homebrew CI, it's still relying on the `ignition` aliases

```
Warning: No available formula with the name "ignition-cmake4".
```

**Review by jennuine — APPROVED** [review]
LGTM, found a couple other places:

- https://github.com/gazebosim/gz-cmake/blob/8fa41235e1fc47bac44f404009af95f75026863b/examples/find_ogre2/ogre-2.1/CMakeLists.txt#L4
- https://github.com/gazebosim/gz-cmake/blob/8fa41235e1fc47bac44f404009af95f75026863b/examples/find_ogre2/ogre-2.2/CMakeLists.txt#L4
- https://github.com/gazebosim/gz-cmake/blob/8fa41235e1fc47bac44f404009af95f75026863b/examples/find_ogre2/ogre-2.3/CMakeLists.txt#L4
- Not sure about here? https://github.com/gazebosim/gz-cmake/blob/main/MigrationFromClassic.md?plain=1#L33

**Comment by jennuine** [comment]
oohh no I didn't see that it was set to auto-merge...

**Comment by chapulina** [comment]
* Voila https://github.com/gazebosim/gz-cmake/pull/299

**Pull request merged**
