### PR TITLE
2 to 3 20220830

### PR DESCRIPTION
**Pull request by nkoenig**
# ➡️ Forward port\

@methylDragon, can you check this to make sure I did this right?

Port ign-cmake2 to gz-cmake3

Branch comparison: https://github.com/gazebosim/gz-cmake/compare/gz-cmake3...ign-cmake2

**Note to maintainers**: Remember to **Merge** with commit (not squash-merge or rebase)

### CODE REVIEW

**Review by methylDragon — APPROVED** [review]
Looks about right! For cmake it's a little different since no `config.hh` files are generated. The moved files have their blames intact too.

Rebase merge could work with this also, if you want to squash any non-moving commits, but aside from that :+1:

**Comment by scpeters** [comment]
no, I thought we intentionally didn't add the `gz/utilities/*` header files on this branch? cc @chapulina

**Comment by scpeters** [comment]
> no, I thought we intentionally didn't add the `gz/utilities/*` header files on this branch? cc @chapulina

but then we backported them in #303, hmm...

**Comment by chapulina** [comment]
Yeah we had skipped them on purpose since they're deprecated. If it makes it easier to have the `gz` counterpart so that everything is consistent across all libraries, I think that's ok though

**Comment by scpeters** [comment]
> Yeah we had skipped them on purpose since they're deprecated. If it makes it easier to have the `gz` counterpart so that everything is consistent across all libraries, I think that's ok though

ok, that was my mistake for not catching that in #303, which we've already released. This is fine

**Review by scpeters — APPROVED** [review]

**Pull request merged**
